#!/usr/bin/env python3

import os
import sys
import json
import subprocess
import time
import socket
import shutil
from pathlib import Path

class SixToFour:
    def __init__(self):
        self.config_dir = "/etc/6to4"
        self.service_dir = "/etc/systemd/system"
        self.configs = {}
        self.ensure_directories()

    def colorize(self, text, color):
        colors = {'red': '\033[91m', 'green': '\033[92m', 'yellow': '\033[93m',
                 'blue': '\033[94m', 'purple': '\033[95m', 'cyan': '\033[96m', 'white': '\033[97m'}
        return f"{colors.get(color, '')}{text}\033[0m"

    def ensure_directories(self):
        """Create necessary directories if they don't exist"""
        os.makedirs(self.config_dir, exist_ok=True)
        os.makedirs(f"{self.config_dir}/configs", exist_ok=True)

    def is_port_open(self, host, port):
        """Check if a port is open on a host"""
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
                sock.settimeout(3)
                result = sock.connect_ex((host, port))
                return result == 0
        except:
            return False

    def get_available_configs(self):
        """Get list of available 6to4 configurations"""
        configs = []
        config_path = f"{self.config_dir}/configs"
        if os.path.exists(config_path):
            for file in os.listdir(config_path):
                if file.endswith('.json'):
                    configs.append(file[:-5])
        return configs

    def load_config(self, config_name):
        """Load a 6to4 configuration"""
        config_file = f"{self.config_dir}/configs/{config_name}.json"
        if os.path.exists(config_file):
            try:
                with open(config_file, 'r') as f:
                    return json.load(f)
            except json.JSONDecodeError:
                print(self.colorize(f"Error: Invalid JSON in {config_file}", 'red'))
                return None
        return None

    def save_config(self, config_name, config_data):
        """Save a 6to4 configuration"""
        config_file = f"{self.config_dir}/configs/{config_name}.json"
        try:
            with open(config_file, 'w') as f:
                json.dump(config_data, f, indent=2)
            return True
        except Exception as e:
            print(self.colorize(f"Error saving config: {e}", 'red'))
            return False

    def create_iran_server_config(self, config_name, iran_ip, foreign_ip):
        """Create Iran server configuration"""
        script_content = f"""#!/bin/bash
# 6to4 Iran Server Configuration
# Generated by SixToFour

# Create 6to4 tunnel
ip tunnel add 6to4_iran mode sit remote {foreign_ip} local {iran_ip}
ip -6 addr add 2002:a00:100::1/64 dev 6to4_iran
ip link set 6to4_iran mtu 1480
ip link set 6to4_iran up

# Create GRE6 tunnel
ip -6 tunnel add GRE6Tun_iran mode ip6gre remote 2002:a00:100::2 local 2002:a00:100::1
ip addr add 10.10.187.1/30 dev GRE6Tun_iran
ip link set GRE6Tun_iran mtu 1436
ip link set GRE6Tun_iran up

# Enable IP forwarding
sysctl net.ipv4.ip_forward=1

# Configure NAT rules
iptables -t nat -A PREROUTING -p tcp --dport 22 -j DNAT --to-destination 10.10.187.1
iptables -t nat -A PREROUTING -j DNAT --to-destination 10.10.187.2
iptables -t nat -A POSTROUTING -j MASQUERADE

echo "6to4 Iran server tunnel started successfully"
"""

        script_path = f"{self.config_dir}/{config_name}_iran.sh"
        try:
            with open(script_path, 'w') as f:
                f.write(script_content)
            os.chmod(script_path, 0o755)
            return script_path
        except Exception as e:
            print(self.colorize(f"Error creating Iran server script: {e}", 'red'))
            return None

    def create_foreign_server_config(self, config_name, iran_ip, foreign_ip):
        """Create Foreign server configuration"""
        script_content = f"""#!/bin/bash
# 6to4 Foreign Server Configuration
# Generated by SixToFour

# Create 6to4 tunnel
ip tunnel add 6to4_Forign mode sit remote {iran_ip} local {foreign_ip}
ip -6 addr add 2002:a00:100::2/64 dev 6to4_Forign
ip link set 6to4_Forign mtu 1480
ip link set 6to4_Forign up

# Create GRE6 tunnel
ip -6 tunnel add GRE6Tun_Forign mode ip6gre remote 2002:a00:100::1 local 2002:a00:100::2
ip addr add 10.10.187.2/30 dev GRE6Tun_Forign
ip link set GRE6Tun_Forign mtu 1436
ip link set GRE6Tun_Forign up

echo "6to4 Foreign server tunnel started successfully"
"""

        script_path = f"{self.config_dir}/{config_name}_foreign.sh"
        try:
            with open(script_path, 'w') as f:
                f.write(script_content)
            os.chmod(script_path, 0o755)
            return script_path
        except Exception as e:
            print(self.colorize(f"Error creating Foreign server script: {e}", 'red'))
            return None

    def create_stop_script(self, config_name, server_type):
        """Create stop script for tunnels"""
        if server_type == "iran":
            tunnel_name = "6to4_iran"
            gre_name = "GRE6Tun_iran"
        else:
            tunnel_name = "6to4_Forign"
            gre_name = "GRE6Tun_Forign"

        script_content = f"""#!/bin/bash
# Stop 6to4 {server_type} server tunnels

# Remove GRE6 tunnel
ip link set {gre_name} down 2>/dev/null
ip tunnel del {gre_name} 2>/dev/null

# Remove 6to4 tunnel
ip link set {tunnel_name} down 2>/dev/null
ip tunnel del {tunnel_name} 2>/dev/null

# Clean up NAT rules (Iran server only)
{'''iptables -t nat -D PREROUTING -p tcp --dport 22 -j DNAT --to-destination 10.10.187.1 2>/dev/null
iptables -t nat -D PREROUTING -j DNAT --to-destination 10.10.187.2 2>/dev/null
iptables -t nat -D POSTROUTING -j MASQUERADE 2>/dev/null''' if server_type == "iran" else ""}

echo "6to4 {server_type} server tunnel stopped"
"""

        script_path = f"{self.config_dir}/{config_name}_{server_type}_stop.sh"
        try:
            with open(script_path, 'w') as f:
                f.write(script_content)
            os.chmod(script_path, 0o755)
            return script_path
        except Exception as e:
            print(self.colorize(f"Error creating stop script: {e}", 'red'))
            return None

    def create_systemd_service(self, config_name, server_type, start_script, stop_script):
        """Create systemd service for 6to4 tunnel"""
        service_content = f"""[Unit]
Description=6to4 Tunnel - {config_name} ({server_type})
After=network.target
Wants=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart={start_script}
ExecStop={stop_script}
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""

        service_name = f"6to4-{config_name}-{server_type}.service"
        service_path = f"{self.service_dir}/{service_name}"

        try:
            with open(service_path, 'w') as f:
                f.write(service_content)

            # Reload systemd and enable service
            subprocess.run(['systemctl', 'daemon-reload'], check=True)
            subprocess.run(['systemctl', 'enable', service_name], check=True)

            return service_name
        except Exception as e:
            print(self.colorize(f"Error creating systemd service: {e}", 'red'))
            return None

    def configure_tunnel(self):
        """Interactive configuration of 6to4 tunnel"""
        print(self.colorize("\n=== 6to4 Tunnel Configuration ===", 'cyan'))

        # Get configuration name
        config_name = input("Enter configuration name: ").strip()
        if not config_name:
            print(self.colorize("Configuration name cannot be empty!", 'red'))
            return False

        # Check if config already exists
        if config_name in self.get_available_configs():
            overwrite = input(f"Configuration '{config_name}' already exists. Overwrite? (y/N): ").strip().lower()
            if overwrite != 'y':
                return False

        # Get server IPs
        print(self.colorize("\n--- Server Information ---", 'yellow'))
        iran_ip = input("Enter Iran server IP: ").strip()
        foreign_ip = input("Enter Foreign server IP: ").strip()

        if not iran_ip or not foreign_ip:
            print(self.colorize("Both server IPs are required!", 'red'))
            return False

        # Validate IP addresses
        try:
            socket.inet_aton(iran_ip)
            socket.inet_aton(foreign_ip)
        except socket.error:
            print(self.colorize("Invalid IP address format!", 'red'))
            return False

        # Ask which server to configure
        print(self.colorize("\n--- Server Type ---", 'yellow'))
        print("1. Iran Server (handles NAT and routing)")
        print("2. Foreign Server (endpoint)")
        print("3. Both Servers")

        choice = input("Select server type to configure (1-3): ").strip()

        config_data = {
            'name': config_name,
            'iran_ip': iran_ip,
            'foreign_ip': foreign_ip,
            'created_at': time.strftime('%Y-%m-%d %H:%M:%S'),
            'services': []
        }

        success = True

        if choice in ['1', '3']:  # Iran server
            print(self.colorize("\nConfiguring Iran server...", 'green'))
            start_script = self.create_iran_server_config(config_name, iran_ip, foreign_ip)
            stop_script = self.create_stop_script(config_name, "iran")

            if start_script and stop_script:
                service_name = self.create_systemd_service(config_name, "iran", start_script, stop_script)
                if service_name:
                    config_data['services'].append({
                        'type': 'iran',
                        'service_name': service_name,
                        'start_script': start_script,
                        'stop_script': stop_script
                    })
                    print(self.colorize(f"Iran server service created: {service_name}", 'green'))
                else:
                    success = False
            else:
                success = False

        if choice in ['2', '3']:  # Foreign server
            print(self.colorize("\nConfiguring Foreign server...", 'green'))
            start_script = self.create_foreign_server_config(config_name, iran_ip, foreign_ip)
            stop_script = self.create_stop_script(config_name, "foreign")

            if start_script and stop_script:
                service_name = self.create_systemd_service(config_name, "foreign", start_script, stop_script)
                if service_name:
                    config_data['services'].append({
                        'type': 'foreign',
                        'service_name': service_name,
                        'start_script': start_script,
                        'stop_script': stop_script
                    })
                    print(self.colorize(f"Foreign server service created: {service_name}", 'green'))
                else:
                    success = False
            else:
                success = False

        if success and self.save_config(config_name, config_data):
            print(self.colorize(f"\n6to4 configuration '{config_name}' created successfully!", 'green'))
            print(self.colorize("Use the service menu to start/stop the tunnels.", 'cyan'))
            return True
        else:
            print(self.colorize("Failed to create 6to4 configuration!", 'red'))
            return False

    def list_configurations(self):
        """List all available 6to4 configurations"""
        configs = self.get_available_configs()
        if not configs:
            print(self.colorize("No 6to4 configurations found.", 'yellow'))
            return

        print(self.colorize("\n=== Available 6to4 Configurations ===", 'cyan'))
        for i, config_name in enumerate(configs, 1):
            config_data = self.load_config(config_name)
            if config_data:
                print(f"\n{i}. {self.colorize(config_name, 'green')}")
                print(f"   Iran IP: {config_data.get('iran_ip', 'N/A')}")
                print(f"   Foreign IP: {config_data.get('foreign_ip', 'N/A')}")
                print(f"   Created: {config_data.get('created_at', 'N/A')}")
                print(f"   Services: {len(config_data.get('services', []))}")

    def check_service_status(self, config_name=None):
        """Check status of 6to4 services"""
        if config_name:
            configs = [config_name]
        else:
            configs = self.get_available_configs()

        if not configs:
            print(self.colorize("No configurations found.", 'yellow'))
            return

        print(self.colorize("\n=== 6to4 Service Status ===", 'cyan'))

        for config_name in configs:
            config_data = self.load_config(config_name)
            if not config_data:
                continue

            print(f"\n{self.colorize(config_name, 'green')}:")

            for service in config_data.get('services', []):
                service_name = service['service_name']
                try:
                    result = subprocess.run(['systemctl', 'is-active', service_name],
                                          capture_output=True, text=True)
                    status = result.stdout.strip()

                    if status == 'active':
                        status_color = 'green'
                    elif status == 'inactive':
                        status_color = 'yellow'
                    else:
                        status_color = 'red'

                    print(f"  {service['type'].capitalize()} Server: {self.colorize(status, status_color)}")

                except Exception as e:
                    print(f"  {service['type'].capitalize()} Server: {self.colorize('error', 'red')}")

    def start_service(self, config_name):
        """Start 6to4 services for a configuration"""
        config_data = self.load_config(config_name)
        if not config_data:
            print(self.colorize(f"Configuration '{config_name}' not found!", 'red'))
            return False

        print(self.colorize(f"Starting 6to4 services for '{config_name}'...", 'green'))

        success = True
        for service in config_data.get('services', []):
            try:
                subprocess.run(['systemctl', 'start', service['service_name']], check=True)
                print(f"  {service['type'].capitalize()} server: {self.colorize('Started', 'green')}")
            except subprocess.CalledProcessError:
                print(f"  {service['type'].capitalize()} server: {self.colorize('Failed to start', 'red')}")
                success = False

        return success

    def stop_service(self, config_name):
        """Stop 6to4 services for a configuration"""
        config_data = self.load_config(config_name)
        if not config_data:
            print(self.colorize(f"Configuration '{config_name}' not found!", 'red'))
            return False

        print(self.colorize(f"Stopping 6to4 services for '{config_name}'...", 'yellow'))

        success = True
        for service in config_data.get('services', []):
            try:
                subprocess.run(['systemctl', 'stop', service['service_name']], check=True)
                print(f"  {service['type'].capitalize()} server: {self.colorize('Stopped', 'yellow')}")
            except subprocess.CalledProcessError:
                print(f"  {service['type'].capitalize()} server: {self.colorize('Failed to stop', 'red')}")
                success = False

        return success

    def restart_service(self, config_name):
        """Restart 6to4 services for a configuration"""
        print(self.colorize(f"Restarting 6to4 services for '{config_name}'...", 'cyan'))
        return self.stop_service(config_name) and self.start_service(config_name)

    def remove_configuration(self, config_name):
        """Remove a 6to4 configuration and its services"""
        config_data = self.load_config(config_name)
        if not config_data:
            print(self.colorize(f"Configuration '{config_name}' not found!", 'red'))
            return False

        # Confirm removal
        confirm = input(f"Are you sure you want to remove '{config_name}' and all its services? (y/N): ").strip().lower()
        if confirm != 'y':
            return False

        print(self.colorize(f"Removing 6to4 configuration '{config_name}'...", 'yellow'))

        # Stop and remove services
        for service in config_data.get('services', []):
            try:
                subprocess.run(['systemctl', 'stop', service['service_name']], check=False)
                subprocess.run(['systemctl', 'disable', service['service_name']], check=False)

                # Remove service file
                service_file = f"{self.service_dir}/{service['service_name']}"
                if os.path.exists(service_file):
                    os.remove(service_file)

                # Remove scripts
                for script_key in ['start_script', 'stop_script']:
                    script_path = service.get(script_key)
                    if script_path and os.path.exists(script_path):
                        os.remove(script_path)

                print(f"  Removed {service['type']} server service")

            except Exception as e:
                print(f"  Error removing {service['type']} server: {e}")

        # Remove configuration file
        config_file = f"{self.config_dir}/configs/{config_name}.json"
        if os.path.exists(config_file):
            os.remove(config_file)

        # Reload systemd
        subprocess.run(['systemctl', 'daemon-reload'], check=False)

        print(self.colorize(f"Configuration '{config_name}' removed successfully!", 'green'))
        return True

    def view_logs(self, config_name):
        """View logs for 6to4 services"""
        config_data = self.load_config(config_name)
        if not config_data:
            print(self.colorize(f"Configuration '{config_name}' not found!", 'red'))
            return

        services = config_data.get('services', [])
        if not services:
            print(self.colorize("No services found for this configuration.", 'yellow'))
            return

        print(self.colorize(f"\n=== Logs for '{config_name}' ===", 'cyan'))

        for service in services:
            print(f"\n{self.colorize(f'{service["type"].capitalize()} Server Logs:', 'green')}")
            try:
                result = subprocess.run(['journalctl', '-u', service['service_name'], '-n', '20', '--no-pager'],
                                      capture_output=True, text=True)
                if result.stdout:
                    print(result.stdout)
                else:
                    print("No logs found.")
            except Exception as e:
                print(f"Error retrieving logs: {e}")

    def check_tunnel_connectivity(self, config_name):
        """Check 6to4 tunnel connectivity"""
        config_data = self.load_config(config_name)
        if not config_data:
            print(self.colorize(f"Configuration '{config_name}' not found!", 'red'))
            return

        print(self.colorize(f"\n=== Connectivity Check for '{config_name}' ===", 'cyan'))

        iran_ip = config_data.get('iran_ip')
        foreign_ip = config_data.get('foreign_ip')

        # Check if IPs are reachable
        print(f"Iran IP ({iran_ip}): ", end="")
        if self.ping_host(iran_ip):
            print(self.colorize("Reachable", 'green'))
        else:
            print(self.colorize("Unreachable", 'red'))

        print(f"Foreign IP ({foreign_ip}): ", end="")
        if self.ping_host(foreign_ip):
            print(self.colorize("Reachable", 'green'))
        else:
            print(self.colorize("Unreachable", 'red'))

        # Check tunnel interfaces
        print("\nTunnel Interfaces:")
        for interface in ['6to4_iran', '6to4_Forign', 'GRE6Tun_iran', 'GRE6Tun_Forign']:
            if self.check_interface_exists(interface):
                print(f"  {interface}: {self.colorize('UP', 'green')}")
            else:
                print(f"  {interface}: {self.colorize('DOWN', 'red')}")

    def ping_host(self, host, count=3):
        """Ping a host to check connectivity"""
        try:
            result = subprocess.run(['ping', '-c', str(count), '-W', '3', host],
                                  capture_output=True, text=True)
            return result.returncode == 0
        except:
            return False

    def check_interface_exists(self, interface):
        """Check if a network interface exists and is up"""
        try:
            result = subprocess.run(['ip', 'link', 'show', interface],
                                  capture_output=True, text=True)
            return result.returncode == 0 and 'UP' in result.stdout
        except:
            return False

    def show_menu(self):
        """Display the main 6to4 menu"""
        while True:
            print(self.colorize("\n=== 6to4 Tunnel Manager ===", 'cyan'))
            print("1. Create New Configuration")
            print("2. List Configurations")
            print("3. Service Management")
            print("4. Check Status")
            print("5. View Logs")
            print("6. Test Connectivity")
            print("7. Remove Configuration")
            print("8. Back to Main Menu")

            choice = input("\nSelect an option (1-8): ").strip()

            if choice == '1':
                self.configure_tunnel()
            elif choice == '2':
                self.list_configurations()
            elif choice == '3':
                self.service_management_menu()
            elif choice == '4':
                self.check_service_status()
            elif choice == '5':
                self.logs_menu()
            elif choice == '6':
                self.connectivity_menu()
            elif choice == '7':
                self.remove_menu()
            elif choice == '8':
                break
            else:
                print(self.colorize("Invalid option! Please try again.", 'red'))

    def service_management_menu(self):
        """Service management submenu"""
        configs = self.get_available_configs()
        if not configs:
            print(self.colorize("No configurations available.", 'yellow'))
            return

        print(self.colorize("\n=== Service Management ===", 'cyan'))
        for i, config in enumerate(configs, 1):
            print(f"{i}. {config}")

        try:
            choice = int(input("\nSelect configuration: ")) - 1
            if 0 <= choice < len(configs):
                config_name = configs[choice]

                print(f"\n=== Managing '{config_name}' ===")
                print("1. Start Services")
                print("2. Stop Services")
                print("3. Restart Services")

                action = input("Select action (1-3): ").strip()

                if action == '1':
                    self.start_service(config_name)
                elif action == '2':
                    self.stop_service(config_name)
                elif action == '3':
                    self.restart_service(config_name)
            else:
                print(self.colorize("Invalid selection!", 'red'))
        except ValueError:
            print(self.colorize("Invalid input!", 'red'))

    def logs_menu(self):
        """Logs viewing submenu"""
        configs = self.get_available_configs()
        if not configs:
            print(self.colorize("No configurations available.", 'yellow'))
            return

        print(self.colorize("\n=== View Logs ===", 'cyan'))
        for i, config in enumerate(configs, 1):
            print(f"{i}. {config}")

        try:
            choice = int(input("\nSelect configuration: ")) - 1
            if 0 <= choice < len(configs):
                self.view_logs(configs[choice])
            else:
                print(self.colorize("Invalid selection!", 'red'))
        except ValueError:
            print(self.colorize("Invalid input!", 'red'))

    def connectivity_menu(self):
        """Connectivity testing submenu"""
        configs = self.get_available_configs()
        if not configs:
            print(self.colorize("No configurations available.", 'yellow'))
            return

        print(self.colorize("\n=== Test Connectivity ===", 'cyan'))
        for i, config in enumerate(configs, 1):
            print(f"{i}. {config}")

        try:
            choice = int(input("\nSelect configuration: ")) - 1
            if 0 <= choice < len(configs):
                self.check_tunnel_connectivity(configs[choice])
            else:
                print(self.colorize("Invalid selection!", 'red'))
        except ValueError:
            print(self.colorize("Invalid input!", 'red'))

    def remove_menu(self):
        """Configuration removal submenu"""
        configs = self.get_available_configs()
        if not configs:
            print(self.colorize("No configurations available.", 'yellow'))
            return

        print(self.colorize("\n=== Remove Configuration ===", 'cyan'))
        for i, config in enumerate(configs, 1):
            print(f"{i}. {config}")

        try:
            choice = int(input("\nSelect configuration to remove: ")) - 1
            if 0 <= choice < len(configs):
                self.remove_configuration(configs[choice])
            else:
                print(self.colorize("Invalid selection!", 'red'))
        except ValueError:
            print(self.colorize("Invalid input!", 'red'))
